apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
      - name: url-shortner-container
        image: pranoyk/url-shortner
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
