// Code generated by MockGen. DO NOT EDIT.
// Source: random_number_generator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRandomNumberGenerator is a mock of RandomNumberGenerator interface.
type MockRandomNumberGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRandomNumberGeneratorMockRecorder
}

// MockRandomNumberGeneratorMockRecorder is the mock recorder for MockRandomNumberGenerator.
type MockRandomNumberGeneratorMockRecorder struct {
	mock *MockRandomNumberGenerator
}

// NewMockRandomNumberGenerator creates a new mock instance.
func NewMockRandomNumberGenerator(ctrl *gomock.Controller) *MockRandomNumberGenerator {
	mock := &MockRandomNumberGenerator{ctrl: ctrl}
	mock.recorder = &MockRandomNumberGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandomNumberGenerator) EXPECT() *MockRandomNumberGeneratorMockRecorder {
	return m.recorder
}

// NewRandomNumber mocks base method.
func (m *MockRandomNumberGenerator) NewRandomNumber(arg0 int64, arg1 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRandomNumber", arg0, arg1)
	ret0, _ := ret[0].(int)
	return ret0
}

// NewRandomNumber indicates an expected call of NewRandomNumber.
func (mr *MockRandomNumberGeneratorMockRecorder) NewRandomNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRandomNumber", reflect.TypeOf((*MockRandomNumberGenerator)(nil).NewRandomNumber), arg0, arg1)
}
